### ISSUE TITLE
Code slower when compiled with ifort instead of gfortran

### ISSUE THREAD

**Issue by mariavd** [qmcurrents/gimic#14] opened 2017-01-12 10:25 UTC
On my laptop I noticed a consistent difference of several seconds in the wall clock time for the two test molecules. It is worth checking and adding appropriate compiler flags to optimize the code. I can do that when I start working on the parallel version.

**Comment by mariavd** [comment] 2017-05-29 09:01
I have been playing with compiler flags on my computer with an Ivy Bridge CPU and when I specified to use AVX instructions the calculations are significantly faster. I did some analyses with Vtune, and I can show you the data if you are interested. For small molecules the code is choking with the exponentials. However, their calculation is significantly faster with the Intel libraries instead of GNU, so it might be useful to offer a binary for download, which has been compiled to work on different architectures. I don't know how to handle the Python integration, though. 

At one point ended up getting segmentation faults. Maybe Intel Fortran is a bit aggressive with -O3 but I am curious to identify what exactly the reason is. The traceback returned this:
```
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source             
libintlc.so.5      00007F292C1A8CF1  tbk_trace_stack_i     Unknown  Unknown
libintlc.so.5      00007F292C1A6E2B  tbk_string_stack_     Unknown  Unknown
libifcoremt.so.5   00007F292DBDC5F2  Unknown               Unknown  Unknown
libifcoremt.so.5   00007F292DBDC446  tbk_stack_trace       Unknown  Unknown
libifcoremt.so.5   00007F292DB350D0  for__issue_diagno     Unknown  Unknown
libifcoremt.so.5   00007F292DB46EB8  for__signal_handl     Unknown  Unknown
libpthread-2.17.s  00007F292BF85370  Unknown               Unknown  Unknown
libgimic2.so       00007F292E0D9FC2  tensor_module_mp_          44  tensor.f90
gimic.bin          000000000042AE2A  jfield_class_mp_j         473  jfield.f90
gimic.bin          0000000000428CCF  jfield_class_mp_j         340  jfield.f90
gimic.bin          0000000000403826  MAIN__                     45  gimic.f90
gimic.bin          00000000004028BE  Unknown               Unknown  Unknown
libc-2.17.so       00007F292B9D2B35  __libc_start_main     Unknown  Unknown
gimic.bin          00000000004027C9  Unknown               Unknown  Unknown
```


My experience with GDB is limited, so maybe I will ask a stupid question. If I just run `gdb gimic` I get this message:
`"/usr/local/bin/gimic": not in executable format: File format not recognized`
So is there some way to get around this Python processing part and just execute gimic.bin? I tried starting a calculation and then stopping it prematurely, so that there will be a GIMIC.in file but running just `gimic.bin` afterwards gives this error that libraries are not found.
```gimic.bin: error while loading shared libraries: libgimic2.so: cannot open shared object file: No such file or directory```

@bast Can something be done about it? I am ready to do some coding if I have an idea what is necessary.

**Comment by mariavd** [comment] 2017-05-30 07:09
@bast  One more question. Why are some runtime paths set to be empty for some libraries and for gimic.bin?

```
-- Installing: /usr/local/lib/python2.7/site-packages/gimic/gimic.so
-- Set runtime path of "/usr/local/lib/python2.7/site-packages/gimic/gimic.so" to ""
-- Installing: /usr/local/lib/python2.7/site-packages/gimic/gengauss.so
-- Set runtime path of "/usr/local/lib/python2.7/site-packages/gimic/gengauss.so" to ""
-- Installing: /usr/local/lib64/libgimic2.so
-- Up-to-date: /usr/local/include/GimicInterface.h
-- Up-to-date: /usr/local/include/gimic_interface.h
-- Up-to-date: /usr/local/include/gimic.pxd
-- Installing: /usr/local/lib/python2.7/site-packages/gimic/connector.so
-- Up-to-date: /usr/local/lib/python2.7/site-packages/gimic/fgimic/__init__.py
-- Installing: /usr/local/lib/python2.7/site-packages/gimic/fgimic/gimic.py
-- Up-to-date: /usr/local/lib/python2.7/site-packages/gimic/fgimic/getkw.py
-- Installing: /usr/local/bin/gimic.bin
-- Set runtime path of "/usr/local/bin/gimic.bin" to ""
```

**Comment by bast** [comment] 2017-05-30 07:10
I have a bit busy week but will write more here later this week.

**Comment by mariavd** [comment] 2017-05-30 07:12
@bast Thank you! Take your time.

**Comment by bast** [comment] 2017-06-27 10:47
Sorry for long wait - not forgotten. I am slowly restarting my work on GIMIC and in the coming weeks will either refactor this code or find an answer to this question.

**Comment by mariavd** [comment] 2017-06-27 11:09
No problem, I should have replied, too, that I did some analysis with VTune and played around with compiler flags, and when compiled with ifort it is now significantly faster. I can send you the VTune outputs if you are curious, and I will be happy to do more if they would be helpful.

________________________________

**Comment by mariavd** [comment] 2017-06-27 11:12
Seems that my memory is getting poor. I completely forgot I mentioned the compiler flags stuff, so I deleted the previous reply. No problem about the delay. In any case, I will be glad to help with something.

**Comment by bast** [comment] 2017-11-30 10:36
I am closing this issue but please reopen if the problem is still there. In this case please submit also an example that demonstrates this.

**Closed as completed by bast** 2017-11-30 10:36 UTC

**Comment by mariavd** [comment] 2017-11-30 13:22
Alright. Actually, when compiled with -xCORE-AVX2 the performance is better than with gcc and -march=native. I should have posted a comment.


30.11.2017 11.37 Radovan Bast <notifications@github.com> kirjoitti:

I am closing this issue but please reopen if the problem is still there. In this case please submit also an example that demonstrates this.
