### ISSUE TITLE
Bug in the scripts

### ISSUE THREAD

**Issue by mariavd** [qmcurrents/gimic#158] opened 2018-03-26 16:17 UTC
I found a bug in the current profile script, so it should be sorted out before somebody ends up with issues. I can modify them in a bit of a stupid way or the other option is to modify the output message for the modulus of the current. At the moment it looks like this:

```
 INFO: Closed-shell calculation

 Integrating current density
 *****************************************
 *** Integrating |J|

 ************************************************************
 Induced mod current (au)   :     0.418819
       Positive contribution:     0.595170  (  16.771552 )
       Negative contribution:    -0.176352  (  -4.969481 )

 Induced mod current (nA/T) :    11.802071
       (conversion factor)  :    28.179409
 ************************************************************


 *** Integrating current

 ************************************************************
    Induced current (au)    :     0.418821
       Positive contribution:     0.595166  (  16.771417 )
       Negative contribution:    -0.176344  (  -4.969283 )

    Induced current (nA/T)  :    11.802134
       (conversion factor)  :    28.179409
 ************************************************************
```

Do you mind if I change it to "Positive mod contribution" and "Negative mod contribution"? 

The problem is that there are two instances of "Positive contribution" in the output file - both for the J and its modulus and when I use grep, it finds both.

**Comment by heikef** [comment] 2018-03-26 18:30
I hesitate changing the gimic output to fit the needs of some scripts. It should be the other way round.

**Comment by mariavd** [comment] 2018-04-04 10:30
If you are willing to accept the bug fix and some other small improvements, including some incomplete work, then I can make a pull request.

**Comment by heikef** [comment] 2018-07-18 13:43
Would it be possible to make sure that the scripts work correctly for integration scans? Then we could advise only using them for this purpose and the rest is at own risk.

**Comment by bast** [comment] 2018-07-18 15:51
But where are two instances of "Positive contribution" in the above script? I see only one.

**Comment by heikef** [comment] 2018-07-19 07:48
There are two if you look into a conventional gimic.out file. One relates to the current density integration and one to the modulus current density integration. Above you see both if you look careful. Just realized that I oversaw it myself while doing the first comment.

**Comment by mariavd** [comment] 2018-07-19 07:55
Yes, I updated the example output. We have a fix for that and we produce plots. I have done more improvements, so Heike could maybe test the scripts from my branch and if all looks good, I will make a PR.

**Comment by heikef** [comment] 2018-07-19 07:58
LOL - thank you for updating the example! I just thought I oversaw it and edited my comment. :)

**Comment by heikef** [comment] 2018-07-19 08:01
Yes, I can do the testing. Pleas tell me the exact branch to use from your fork.

**Comment by heikef** [comment] 2018-07-19 08:03
I assume your fork is then identical to gimic master branch and only differs with respect to the scripts?

**Comment by bast** [comment] 2018-07-19 08:14
When you wrote 'Do you mind if I change it to "Positive mod contribution" and "Negative mod contribution"?' did you mean changing "positive contribution" to "positive mod contribution"?

**Comment by heikef** [comment] 2018-07-19 08:19
Yes, I understood it at least this way when commenting.

**Comment by heikef** [comment] 2018-07-19 08:42
This is a bit off topic therefore I filled an extra issue #181 but it came to my mind when a user is happy with less script features that we offer in the bash scripts it should be rather straight forward to adapt the giba.py scripts from Raul.

**Comment by bast** [comment] 2018-07-19 09:09
If it was meant that way, then yes, I am all for it. I got really confused by the suggestion changing positive to negative which was probably not meant.

**Comment by heikef** [comment] 2018-07-19 09:13
I think we should not change the gimic output according to requests from scripts. It used to be possible for example to switch the modulus option off and there is the giba script that would also need to be adapted if we start to change the gimic output.

**Comment by bast** [comment] 2018-07-19 09:24
The suggestion would make the output easier to parse. The output will evolve and scripts that parse it need to adapt. Of course we need to minimize unnecessary changes which break clients.

**Comment by heikef** [comment] 2018-07-19 10:16
As I understood this change is not needed any more. If we start changing it now it would only unnecessarily complicate things.

**Comment by mariavd** [comment] 2018-07-20 05:37
Yes, I had asked about changing "positive contribution" to "positive mod contribution". It saves extra piping in the script but since you don't like the change it can stay.

**Comment by bast** [comment] 2018-07-20 06:38
Well FWIW I like this suggested change. But if this change is rejected, can this issue please be closed?

**Comment by mariavd** [comment] 2018-07-20 07:12
Heike can decide.

**Comment by heikef** [comment] 2018-07-20 09:05
I would prefer to close the issue when the scripts are tested and work for the integration. We should have working scripts as part of our "master" branch, which is currently not the case. This issue is not about changing gimic output but about fixing a bug on the master branch. I offered to help with testing but I need to know which branch to use from Maria's fork. Could you simply file a pull request? Thank you.

**Comment by heikef** [comment] 2018-07-20 09:10
Ok it is scripts-clean. I will work on it.

**Comment by bast** [comment] 2018-07-20 09:14
I think this was a suggestion to change the output.

**Comment by heikef** [comment] 2018-07-20 09:20
The issue is about fixing some bugs in the scripts such that the integration scan, which is the most relevant for a user works. There are more fancy options regarding the scripts in the making as I understood, which is a cool thing.

**Comment by bast** [comment] 2018-07-20 09:23
But this suggestion is really about changing GIMIC output :-)

**Comment by heikef** [comment] 2018-07-20 09:27
No it is not. The scripts have been adapted. They work without changing the gimic output. Testing is now a task, which is on my desk.

**Comment by heikef** [comment] 2018-07-20 09:54
Perhaps it would be better to switch the calculation of the modulus integration off instead of changing the output. This would save more time.

**Comment by heikef** [comment] 2018-07-20 10:02
filled #182 since this is an extra issue

**Comment by mariavd** [comment] 2018-07-20 11:49
Initially the issue was asking to change the input. I have a workaround which is not optimal but works. If at some point the change would be considered, then I can improve the line which parses the gimic output.

**Comment by bast** [comment] 2018-07-20 13:26
This issue addresses a change in the GIMIC output. The title of this issue as well as some of the descriptions are unfortunate. I would welcome this change in GIMIC output but if you prefer to not do this, then please close this issue.

**Comment by heikef** [comment] 2018-07-20 13:36
Hm, I disagree but am fine with closing the issue. :)

**Closed as completed by heikef** 2018-07-20 13:36 UTC
