### ISSUE TITLE
CMake Error at GIMIC installation

### ISSUE THREAD

**Issue by MesiasOrozco** [qmcurrents/gimic#215] opened 2019-03-12 22:27 UTC
Hi, I have a problem when I am trying to install gimic.

Installation is running but crashes with this:

fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
CMake Error at cmake/custom/git.cmake:9 (string):
  string sub-command STRIP requires two arguments.
Call Stack (most recent call first):
  cmake/custom/own.cmake:6 (include)
  CMakeLists.txt:104 (include)

CMake Error at /Users/mesiasorozco/psi4conda/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find Python (missing: PYTHON_LIBRARY)
Call Stack (most recent call first):
  /Users/mesiasorozco/psi4conda/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  cmake/custom/FindPython.cmake:141 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  cmake/custom/cython.cmake:75 (find_package)
  cmake/custom/own.cmake:11 (include)
  CMakeLists.txt:104 (include)
 

I would really appreciate to find a solution.

**Comment by bast** [comment] 2019-03-13 08:16
Thanks for reporting! I will look at the first problem - this rings a bell. I thought I fixed that but I will double check.

To debug the second problem, CMake complains that it cannot find the Python library. First of all on what kind of a system are you experiencing this?

**Comment by bast** [comment] 2019-03-13 08:22
I just checked the first problem quickly and cannot reproduce it. Which version of GIMIC are you using? How did you download it and how can you post step by step how I can reproduce this? From download step all the way to the error.

**Comment by MesiasOrozco** [comment] 2019-03-13 16:59
Hi, thank you by the answer. Sorry, I didn't say that I am running this in an IOs mac. I download GIMIC directly from https://github.com/qmcurrents/gimic . So I think that it is the last version.

Thank you

**Comment by bast** [comment] 2019-03-14 09:33
How do you download the code? With git clone?

And how did you install Python? My recommendation is to install using `brew`, this should also install the Python libraries. [Disclaimer: I am not a macOS user so I cannot easily verify my claim here]

**Comment by MesiasOrozco** [comment] 2019-03-19 16:34
Thanks, I employed brew. So, do you think that is a problem of python or CMake then?.

Thank you in advice.

**Comment by bast** [comment] 2019-03-19 19:28
Where is the Python library? It seems CMake cannot find it.
Please try to locate `Python.h` and `libpython*.dylib` on your system.

**Comment by heikef** [comment] 2019-03-27 09:33
For me installing Anaconda worked out. Then most of the other stuff required for gimic like cython is either already available or quickly installed and one does not have to bother about the paths.

**Comment by heikef** [comment] 2019-03-29 13:50
Is this issue resolved?

**Comment by heikef** [comment] 2019-03-30 16:22
Since I do not get an answer I will close the issue. We can always reopen it if needed be.

**Closed as completed by heikef** 2019-03-30 16:22 UTC
